#!/usr/bin/expect -f

set timeout 20
set hostname [lindex $argv 0]
set username [lindex $argv 1]
set password [lindex $argv 2]

set timeout -1
spawn ssh -q -o StrictHostKeyChecking=no $username@$hostname
expect "password: "
send "$password\r"
expect "> "
send "racadm set iDRAC.IPMISol.Enable 1\r"
expect "> "
send "racadm set iDRAC.IPMISol.MinPrivilege 1\r"
expect "> "
send "racadm set iDRAC.IPMISol.BaudRate 115200\r"
expect "> "
send "racadm set set iDRAC.Users.1.SolEnable 4\r"
expect "> "

