#!/usr/bin/expect -f

set timeout 20
set hostname [lindex $argv 0]
set username [lindex $argv 1]
set password [lindex $argv 2]


spawn ssh -q -o StrictHostKeyChecking=no $username@$hostname
expect "password: "
send "$password\r"
expect {
 "racadm>>" { set delim "racadm>>" }
 "admin1->"  { set delim "admin1->" }
}
send "racadm set LifecycleController.LCAttributes.LifecycleControllerState 1\r"
expect "$delim"
